-- TAXI_SHAPOSHNIKOV.TOP5ADDRESS source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TAXI_SHAPOSHNIKOV"."TOP5ADDRESS" ("PASSENGER_NAME", "ADDR") AS 
  SELECT p.PASSENGER_NAME, t.addr FROM (
SELECT io.PASSENGER_ID, w.TO_ADDRESS_ID AS addr, count (w.TO_ADDRESS_ID) AS cnt   FROM IS_ORDER io
left OUTER  JOIN way w ON w.ORDER_ID = io.ID 
GROUP BY io.PASSENGER_ID, w.TO_ADDRESS_ID
HAVING count (w.TO_ADDRESS_ID) > 1
ORDER BY 1 ASC) t
JOIN PASSENGER p ON p.ID = t.PASSENGER_ID
GROUP BY p.PASSENGER_NAME, t.addr
ORDER BY 1,2 ASC;