-- TAXI_SHAPOSHNIKOV.DONUTS source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TAXI_SHAPOSHNIKOV"."DONUTS" ("AVG_PAY", "COUNTRY") AS 
  SELECT min(p.AMOUNT_TO_PAID) AS AVG_PAY, c.NAME AS COUNTRY  FROM PAYMENT p 
	INNER JOIN CURRENCY2COUNTRY cc ON p.CURRENCY_ID = cc.CURRENCY_ID 
	INNER JOIN COUNTRY c ON cc.COUNTRY_ID = c.ID
	GROUP BY cc.CURRENCY_ID, c.NAME;