-- TAXI_SHAPOSHNIKOV.NEWDRIVERS source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TAXI_SHAPOSHNIKOV"."NEWDRIVERS" ("PASSENGER_NAME", "FF") AS 
  SELECT 
	DISTINCT (p.PASSENGER_NAME), (SELECT LISTAGG(d.NAME,', ') FROM DRIVER d WHERE d.ID NOT IN (SELECT io.DRIVER_ID FROM IS_ORDER io)) AS ff
		FROM IS_ORDER e
			inner JOIN PASSENGER p ON p.ID = e.PASSENGER_ID
			inner JOIN DRIVER d ON d.ID = e.DRIVER_ID
		GROUP BY  p.PASSENGER_NAME, d.NAME
	ORDER BY 1,2;