CREATE TABLE "TAXI_SHAPOSHNIKOV"."ADDRESS" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"HOUSE_NUMBER" NUMBER(38,0) NOT NULL ENABLE, 
	"STREET_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."ADDRESS" ADD CONSTRAINT "FK_STREET" FOREIGN KEY ("STREET_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."STREET" ("ID") ON DELETE CASCADE ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."ADDRESS_T1" 
BEFORE
insert or update or delete on "ADDRESS"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."ADDRESS_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."ADDRESS_PK" ON "TAXI_SHAPOSHNIKOV"."ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."CAR" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CAR_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"BRAND" VARCHAR2(50) NOT NULL ENABLE, 
	"MODEL" VARCHAR2(50) NOT NULL ENABLE, 
	"COLOR" VARCHAR2(50) NOT NULL ENABLE, 
	"IS_RESERVED" NUMBER NOT NULL ENABLE, 
	"STATE_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"PARKING_ID" NUMBER NOT NULL ENABLE, 
	"MILEAGE" NUMBER, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "CAR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."CAR_T1" 
BEFORE
insert or update or delete on "CAR"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."CAR_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."CAR_PK" ON "TAXI_SHAPOSHNIKOV"."CAR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."CITY" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"COUNTRY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "CITY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."CITY" ADD CONSTRAINT "FK_COUNTRY" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."COUNTRY" ("ID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."CITY_PK" ON "TAXI_SHAPOSHNIKOV"."CITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."COUNTRY" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."COUNTRY_PK" ON "TAXI_SHAPOSHNIKOV"."COUNTRY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."CURRENCY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"ABBREVIATION" VARCHAR2(8) NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "CURRENCY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."CURRENCY_T1" 
BEFORE
insert or update or delete on "CURRENCY"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."CURRENCY_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."CURRENCY_PK" ON "TAXI_SHAPOSHNIKOV"."CURRENCY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."CURRENCY2COUNTRY" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CURRENCY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"COUNTRY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	 CONSTRAINT "CURRENCY2COUNTRY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."CURRENCY2COUNTRY" ADD CONSTRAINT "FK_CURRENCY_ID" FOREIGN KEY ("CURRENCY_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."CURRENCY" ("ID") ENABLE;
  ALTER TABLE "TAXI_SHAPOSHNIKOV"."CURRENCY2COUNTRY" ADD CONSTRAINT "FK_COUNTRY_ID" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."COUNTRY" ("ID") ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."CURRENCY2COUNTRY_PK" ON "TAXI_SHAPOSHNIKOV"."CURRENCY2COUNTRY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TAXI_SHAPOSHNIKOV"."DONUTS" ("AVG_PAY", "COUNTRY") AS 
  SELECT min(p.AMOUNT_TO_PAID) AS AVG_PAY, c.NAME AS COUNTRY  FROM PAYMENT p 
	INNER JOIN CURRENCY2COUNTRY cc ON p.CURRENCY_ID = cc.CURRENCY_ID 
	INNER JOIN COUNTRY c ON cc.COUNTRY_ID = c.ID
	GROUP BY cc.CURRENCY_ID, c.NAME;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."DRIVER" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(250) NOT NULL ENABLE, 
	"AGE" NUMBER NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"PERCENT_OF_PAYMENT" NUMBER NOT NULL ENABLE, 
	"REGISTRATION_DATE" DATE NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	 CONSTRAINT "DRIVER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."DRIVER_T1" 
BEFORE
insert or update or delete on "DRIVER"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."DRIVER_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."DRIVER_PK" ON "TAXI_SHAPOSHNIKOV"."DRIVER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE TAXI_SHAPOSHNIKOV.DRIVER_IMAGE;

CREATE TABLE TAXI_SHAPOSHNIKOV.DRIVER_IMAGE (
	ID NUMBER(38,0) NOT NULL,
	IMAGE CLOB NULL,
	TIME_CREATE TIMESTAMP NULL,
	CONSTRAINT SYS_C00165662 CHECK ("ID" IS NOT NULL)
);
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."DRIVER_RATING" 
   (	"DRIVER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RATING" NUMBER(38,0), 
	"TIME_CREATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."DRIVER_RATING" ADD CONSTRAINT "FK_DRIVER_RATING" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."DRIVER" ("ID") ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."DRIVER_RATING_T1" 
BEFORE
insert or update or delete on "DRIVER_RATING"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."DRIVER_RATING_T1" ENABLE;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."IS_ORDER" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PASSENGER_ID" NUMBER NOT NULL ENABLE, 
	"DRIVER_ID" NUMBER NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"TIME_END" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"PAYMENT_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"END_TRIP_ADDRESS" NUMBER, 
	"AVERAGE_DRIVER_SPEED" FLOAT(2), 
	 CONSTRAINT "IS_ORDER_STATUS_CHANGE" CHECK (status IN ('search_driver','wait_driver','wait_passenger','trip_started','trip_completed','canceled','wait_payment')) ENABLE, 
	 CONSTRAINT "IS_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."IS_ORDER" ADD CONSTRAINT "FK_ISORDER_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."DRIVER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TAXI_SHAPOSHNIKOV"."IS_ORDER" ADD CONSTRAINT "FK_ISORDER_PASSENGER" FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."PASSENGER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TAXI_SHAPOSHNIKOV"."IS_ORDER" ADD CONSTRAINT "FK_PAYMENT" FOREIGN KEY ("PAYMENT_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."PAYMENT" ("ID") ON DELETE CASCADE ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."IS_ORDER_T1" 
BEFORE
insert or update or delete on "IS_ORDER"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;

/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."IS_ORDER_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."IS_ORDER_PK" ON "TAXI_SHAPOSHNIKOV"."IS_ORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."N3P1" 
   (	"STEP" NUMBER(38,0), 
	"N" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TAXI_SHAPOSHNIKOV"."NEWDRIVERS" ("PASSENGER_NAME", "FF") AS 
  SELECT 
	DISTINCT (p.PASSENGER_NAME), (SELECT LISTAGG(d.NAME,', ') FROM DRIVER d WHERE d.ID NOT IN (SELECT io.DRIVER_ID FROM IS_ORDER io)) AS ff
		FROM IS_ORDER e
			inner JOIN PASSENGER p ON p.ID = e.PASSENGER_ID
			inner JOIN DRIVER d ON d.ID = e.DRIVER_ID
		GROUP BY  p.PASSENGER_NAME, d.NAME
	ORDER BY 1,2;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."PARKING" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"number" NUMBER(38,0) NOT NULL ENABLE, 
	"ADDRESS_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6), 
	 CONSTRAINT "PARKING_UN" UNIQUE ("number")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."PARKING" ADD CONSTRAINT "FK_ADDRESS" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."ADDRESS" ("ID") ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."PARKING" 
BEFORE
insert or update or delete on "PARKING"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."PARKING" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."PARKING_UN" ON "TAXI_SHAPOSHNIKOV"."PARKING" ("number") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."PASSENGER" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"IS_ANON" NUMBER(1,0) NOT NULL ENABLE, 
	"PASSENGER_NAME" VARCHAR2(250), 
	"AGE" NUMBER, 
	"HOME_ADDRESS_ID" NUMBER, 
	"PHONE_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"IS_MALE" NUMBER(1,0), 
	"TIME_CREATE" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PASSENGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."PASSENGER_T1" 
BEFORE
insert or update or delete on "PASSENGER"
for each row

BEGIN
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
END;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."PASSENGER_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."PASSENGER_PK" ON "TAXI_SHAPOSHNIKOV"."PASSENGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE TAXI_SHAPOSHNIKOV.PASSENGER_IMAGE;

CREATE TABLE TAXI_SHAPOSHNIKOV.PASSENGER_IMAGE (
	ID NUMBER(38,0) NOT NULL,
	TIME_CREATE TIMESTAMP NULL,
	IMAGE CLOB NULL,
	CONSTRAINT PASSENGER_IMAGE_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C00165655 CHECK ("ID" IS NOT NULL)
);
CREATE UNIQUE INDEX PASSENGER_IMAGE_PK ON TAXI_SHAPOSHNIKOV.PASSENGER_IMAGE (ID);
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."PASSENGER_RATING" 
   (	"PASSENGER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RATING" NUMBER(38,0), 
	"TIME_CREATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."PASSENGER_RATING" ADD CONSTRAINT "FK_PASSENGER" FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."PASSENGER" ("ID") ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."PASSENGER_RATING_T1" 
BEFORE
insert or update or delete on "PASSENGER_RATING"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."PASSENGER_RATING_T1" ENABLE;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."PAYMENT" 
   (	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"CURRENCY_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"AMOUNT_TO_PAID" FLOAT(126), 
	 CONSTRAINT "PAYMENT_CHECK" CHECK (TYPE IN ('CARD','CASH')) ENABLE, 
	 CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."PAYMENT_T1" 
BEFORE
insert or update or delete on "PAYMENT"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;

/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."PAYMENT_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."PAYMENT_PK" ON "TAXI_SHAPOSHNIKOV"."PAYMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."RATE" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CURRENCY1_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"CURRENCY2_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RATE" NUMBER(38,0), 
	"TIME_CREATE" TIMESTAMP (6), 
	 CONSTRAINT "RATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."RATE" ADD CONSTRAINT "FK_CURRENCY_1" FOREIGN KEY ("CURRENCY1_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."CURRENCY" ("ID") ENABLE;
  ALTER TABLE "TAXI_SHAPOSHNIKOV"."RATE" ADD CONSTRAINT "FK_CURRENCY_2" FOREIGN KEY ("CURRENCY2_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."CURRENCY" ("ID") ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."RATE_T1" 
BEFORE
insert or update or delete on "RATE"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."RATE_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."RATE_PK" ON "TAXI_SHAPOSHNIKOV"."RATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."RATING_DRIVER2PASSANGER" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"PASSANGER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"DRIVER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"RATING" NUMBER(38,0), 
	"TIME_CREATE" TIMESTAMP (6), 
	 CONSTRAINT "RATING_DRIVER2PASSANGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."RATING_DRIVER2PASSANGER" ADD CONSTRAINT "FK_DRIVER_2" FOREIGN KEY ("ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."DRIVER" ("ID") ENABLE;
  ALTER TABLE "TAXI_SHAPOSHNIKOV"."RATING_DRIVER2PASSANGER" ADD CONSTRAINT "FK_PASSENGER_2" FOREIGN KEY ("ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."PASSENGER" ("ID") ENABLE;
  ALTER TABLE "TAXI_SHAPOSHNIKOV"."RATING_DRIVER2PASSANGER" ADD CONSTRAINT "FK_IS_ORDER_2" FOREIGN KEY ("ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."IS_ORDER" ("ID") ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."RATING_T1" 
BEFORE
insert or update or delete on "RATING_DRIVER2PASSANGER"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;
/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."RATING_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."RATING_DRIVER2PASSANGER_PK" ON "TAXI_SHAPOSHNIKOV"."RATING_DRIVER2PASSANGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."REFUELLING" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DRIVER_ID" NUMBER NOT NULL ENABLE, 
	"CAR_ID" NUMBER NOT NULL ENABLE, 
	"PAYMENT_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"AMOUNT_OF_GASOLINE" FLOAT(126) NOT NULL ENABLE, 
	"ADDRESS_ID" NUMBER NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."REFUELLING_T1" 
BEFORE
insert or update or delete on "REFUELLING"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;

/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."REFUELLING_T1" ENABLE;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."RENT" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DRIVER_ID" NUMBER NOT NULL ENABLE, 
	"CAR_ID" NUMBER NOT NULL ENABLE, 
	"DATE_START" DATE NOT NULL ENABLE, 
	"DATE_STOP" DATE, 
	"GAS_MILEAGE" NUMBER, 
	"DISTANCE" NUMBER, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "RENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."RENT" ADD CONSTRAINT "FK_CAR" FOREIGN KEY ("CAR_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."CAR" ("ID") ENABLE;
  ALTER TABLE "TAXI_SHAPOSHNIKOV"."RENT" ADD CONSTRAINT "FK_DRIVER" FOREIGN KEY ("DRIVER_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."DRIVER" ("ID") ON DELETE CASCADE ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "TAXI_SHAPOSHNIKOV"."RENT_T1" 
BEFORE
insert or update or delete on "RENT"
for each row
begin
   -- обновить поле create_date на текущую системную дату
   :new.time_create := sysdate;
end;

/
ALTER TRIGGER "TAXI_SHAPOSHNIKOV"."RENT_T1" ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."RENT_PK" ON "TAXI_SHAPOSHNIKOV"."RENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE TABLE "TAXI_SHAPOSHNIKOV"."STREET" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CITY_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"TIME_CREATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "STREET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;

ALTER TABLE "TAXI_SHAPOSHNIKOV"."STREET" ADD CONSTRAINT "FK_CITY" FOREIGN KEY ("CITY_ID")
	  REFERENCES "TAXI_SHAPOSHNIKOV"."CITY" ("ID") ENABLE;

CREATE UNIQUE INDEX "TAXI_SHAPOSHNIKOV"."STREET_PK" ON "TAXI_SHAPOSHNIKOV"."STREET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_40800620212169733" ;
;

CREATE OR REPLACE FORCE EDITIONABLE VIEW "TAXI_SHAPOSHNIKOV"."TOP5ADDRESS" ("PASSENGER_NAME", "ADDR") AS 
  SELECT p.PASSENGER_NAME, t.addr FROM (
SELECT io.PASSENGER_ID, w.TO_ADDRESS_ID AS addr, count (w.TO_ADDRESS_ID) AS cnt   FROM IS_ORDER io
left OUTER  JOIN way w ON w.ORDER_ID = io.ID 
GROUP BY io.PASSENGER_ID, w.TO_ADDRESS_ID
HAVING count (w.TO_ADDRESS_ID) > 1
ORDER BY 1 ASC) t
JOIN PASSENGER p ON p.ID = t.PASSENGER_ID
GROUP BY p.PASSENGER_NAME, t.addr
ORDER BY 1,2 ASC;
;

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE TAXI_SHAPOSHNIKOV.WAY;

CREATE TABLE TAXI_SHAPOSHNIKOV.WAY (
	ID NUMBER DEFAULT "TAXI_SHAPOSHNIKOV"."ISEQ$$_195698".nextval NOT NULL,
	FROM_ADDRESS_ID NUMBER(38,0) NOT NULL,
	TO_ADDRESS_ID NUMBER(38,0) NOT NULL,
	DISTANCE NUMBER(38,0) NOT NULL,
	ORDER_ID NUMBER(38,0) NOT NULL,
	PREVIEW_WAY_ID NUMBER(38,0) NULL,
	TIME_CREATE TIMESTAMP WITH LOCAL TIME ZONE NULL,
	POINT_TO_GO TAXI_SHAPOSHNIKOV.ADDR_POINTS NULL,
	CONSTRAINT SYS_C00121606 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C00121607 CHECK ("FROM_ADDRESS_ID" IS NOT NULL),
	CONSTRAINT SYS_C00121610 CHECK ("ORDER_ID" IS NOT NULL),
	CONSTRAINT SYS_C00142940 CHECK ("TO_ADDRESS_ID" IS NOT NULL),
	CONSTRAINT SYS_C00142941 CHECK ("DISTANCE" IS NOT NULL),
	CONSTRAINT WAY_PK PRIMARY KEY (ID),
	CONSTRAINT FK_ADDRESS_PREVIEW_ID FOREIGN KEY (PREVIEW_WAY_ID) REFERENCES TAXI_SHAPOSHNIKOV.ADDRESS(ID),
	CONSTRAINT FK_FROM_ADDRESS FOREIGN KEY (FROM_ADDRESS_ID) REFERENCES TAXI_SHAPOSHNIKOV.ADDRESS(ID),
	CONSTRAINT FK_IS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES TAXI_SHAPOSHNIKOV.IS_ORDER(ID) ON DELETE CASCADE,
	CONSTRAINT FK_TO_ADDRESS FOREIGN KEY (TO_ADDRESS_ID) REFERENCES TAXI_SHAPOSHNIKOV.ADDRESS(ID)
);
CREATE UNIQUE INDEX WAY_PK ON TAXI_SHAPOSHNIKOV.WAY (ID);
;